name: Auto Update TRAEX AI Site

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # Daily at 6AM IST

permissions:
  contents: write

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "TRAEX AI Bot"
          git config user.email "bot@traex.global"

      - name: Fetch latest index.html from AI
        run: |
          curl -fLo index.html https://raw.githubusercontent.com/Amaran-g/traex-ai/main/index.html

      - name: Commit & Push
        run: |
          git add index.html
          git commit -m "🤖 Auto-update: refreshed index.html from AI" || echo "No changes to commit"
          git push
