name: Auto Update TRAEX AI Site

# ensure this workflow can write files (commits/push)
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # every day at 6:00 IST

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Git
        run: |
          git config user.name "TRAEX AI Bot"
          git config user.email "bot@traex.global"

      - name: Fetch latest index.html from repo
        run: |
          curl -L -o index.html https://raw.githubusercontent.com/Amaran-g/traex-ai/main/index.html

      - name: Commit & Push
        run: |
          git add index.html
          git commit -m "🤖 Auto-update: refreshed index.html" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Deploy to Vercel
        if: success()
        run: |
          echo "Deploying to Vercel..."
          npm install -g vercel
          vercel deploy --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
